// <auto-generated />
namespace HospitalLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Versao2011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Versao2011));
        
        string IMigrationMetadata.Id
        {
            get { return "201707040537124_Versao2.0.1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
